# Configs for pwills.com

title: "Christian's Site"
name: "pwills.com"
email: peter@pwills.com
url: "http://www.pwills.com"
repository: "peterewills/peterewills.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Christian Rummler"
  avatar : "https://media.licdn.com/dms/image/C4D03AQEa2dQIbTWdUQ/profile-displayphoto-shrink_800_800/0/1668027077320?e=1703116800&v=beta&t=qwQ7DzmC6l80pBdhAamSqnAn1VD2ytE6iteK_e28aL0"
  bio    : "Learning about Tech!"
  location: "Downers Grove, IL"
  github : z1938435
  linkedin: christianrummler
  email  : christianrrummler@gmail.com


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "pwills-com"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
